name: db
on:
  workflow_dispatch:
  schedule:
  - cron: '0 5 * * *'
jobs:
  db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Autoclean
        run: |
          sudo apt clean -y 
          sudo apt autoclean -y 
          sudo apt autoremove -y
          sudo apt update
          sudo apt install --fix-missing
      - name: Install dependencies
        run: sudo apt install -y pgloader sqlite3
      - name: Build DB
        env:
          DB_TARGET: ${{ secrets.DB_TARGET }}
        run: ./db/populate.sh
